window.WORKS = {
  name: "苏琦珺",
  domain: "xiaoyeeat.cn",
  icp: "琼ICP备2026010389号-1",
  icpHref: "https://beian.miit.gov.cn/",
  lede: "菜鸟两年，做内部 CRM 的线索与商机；后来做过一段时间字节房产经营系统。这里放我做成的 AI 文章和应用。",
  about: "我是产品经理，做过 ToB 线索与经营系统。主线是线索清洗：一篇讲怎么想，一个外呼应用可以试；另有物流行业一文。",
  ctaPrimary: "看作品",
  ctaSecondary: "试外呼应用",
  pair: {
    title: "线索清洗",
    note: "同一件事的两种形态：左边是怎么想的，右边是可以打一通的测试台。",
    article: {
      id: "lead-cleaning",
      kind: "文章",
      title: "用 AI 做线索清洗：外呼前置判断",
      summary: "清洗发生在去重之后、分配之前。规则剔不干净，真人逐个确认又贵又慢。这篇写 AI 外呼要配齐哪些能力，以及怎么验效果。",
      time: "约 25 分钟",
    },
    lab: {
      id: "lianyi",
      kind: "可试",
      title: "线索清洗外呼测试台",
      summary: "你扮演客户接听。AI「小陈」确认寄件需求，挂机后生成可抽检的拜访小记。浏览器模拟电话，不是真实线路。",
      time: "约 5 分钟",
    },
  },
  articles: [
    {
      id: "logistics-sales",
      kind: "文章",
      title: "物流行业的销售流程、场景卡点与 AI 方案",
      summary: "物流不是一条销售流程。按仓配及周边、快递、物流科技分开看卡点，再判断哪里适合用 AI，哪里不该上模型。",
      time: "约 22 分钟",
    },
  ],
  articleBodies: {
    "lead-cleaning": {
      title: "用 AI 做线索清洗：外呼前置判断",
      toc: [
        { id: "intro", label: "开篇" },
        { id: "part-1", label: "清洗在链路中的位置" },
        { id: "part-2", label: "从人工到 AI 外呼" },
        { id: "part-3", label: "落地需要哪些能力" },
      ],
      blocks: [
        { type: "h2", id: "intro", text: "开篇" },
        { type: "p", text: "销售流程整体可以分为线索挖掘、商机跟进、合同签约。其中如何高效完成线索清洗，一直是挖掘阶段的痛点。" },
        { type: "p", text: "传统办法大致两种：人工逐个打电话确认；或用硬规则剔掉明显不合格的线索。规则能剔除的量有限；真人逐个外呼又很费时间。以我曾供职的公司为例，销售每天早上常要花约两个小时打电话做清洗。" },
        { type: "p", text: "AI 提供第三种做法：把 AI 做成类似市场部员工的角色，替代真人打电话确认。" },
        { type: "h2", id: "part-1", text: "清洗在线索处理链路中的位置" },
        { type: "p", text: "整条线索处理通常包括六步：入库、去重、清洗、分配、跟进、转化。用 AI 外呼辅助清洗，发生在第 3 步：线索去重之后、线索分配之前。" },
        { type: "h2", id: "part-2", text: "从人工清洗到 AI 外呼" },
        { type: "p", text: "最初是销售自己用手机拨打、自行判断。随后清洗被单独分出，交给市场部或外包。再往后，线路从个人手机转到云呼叫，并开始录音、转写、抽字段。再进一步，连谁来打电话也可以交给 AI。" },
        { type: "h2", id: "part-3", text: "落地需要哪些产品能力" },
        { type: "p", text: "主要是三块，配齐后再持续验效果：自动外呼、AI 外呼客服、基于通话文本的拜访小记。深度跟进与成交仍由人工销售承接。" },
      ],
      footnote: "原型里只放开头几段，方便感受阅读页。正式上线会放进现有全文 HTML，并加上这一条返回目录的顶栏。",
    },
    "logistics-sales": {
      title: "物流行业的销售流程、场景卡点与 AI 方案",
      toc: [
        { id: "intro", label: "开篇" },
        { id: "part-1", label: "业务类型" },
        { id: "part-2", label: "销售链路" },
        { id: "part-3", label: "流程卡点" },
        { id: "part-4", label: "针对卡点的方案" },
      ],
      blocks: [
        { type: "h2", id: "intro", text: "开篇" },
        { type: "p", text: "本文有两层动机。第一层，以物流为例，看 AI 在销售流程里能帮到哪、帮到什么程度。第二层，落到细分场景：按行业特性与销售流程差异找卡点，再匹配解题方式——包括 AI，也包括不宜上模型时的其他手段。" },
        { type: "p", text: "有两点值得先记住。AI 不是万能的，面对不同卡点应组合规则、权限、系统打通与模型。当使用 AI 时，它更适合做初判、草稿、预填、预审和整理；不宜代替与业绩分配相关的资源调配，也不能代替审批里需要由人承担的责任。" },
        { type: "h2", id: "part-1", text: "业务类型" },
        { type: "p", text: "分类前提是销售流程是否一致。按此分为三类：仓配及周边、快递、物流科技（非仓配增值）。合同物流、供应链外包归入仓配及周边；退货方案、绿色包材等是仓配主合同的附加，不单开冷启动链路。" },
      ],
      footnote: "原型节选。正式页沿用现有带目录的长文 HTML。",
    },
  },
  routes: [
    { path: "/", kind: "静态", title: "首页目录", note: "姓名、一段介绍、作品列表" },
    { path: "/articles/lead-cleaning", kind: "静态", title: "线索清洗一文", note: "现有 HTML + 站点顶栏" },
    { path: "/articles/logistics-sales", kind: "静态", title: "物流销售一文", note: "现有 HTML + 站点顶栏" },
    { path: "/lab/lianyi", kind: "静态", title: "测试台说明页", note: "先讲清怎么试，再进应用" },
    { path: "/lab/lianyi/call", kind: "反代", title: "链驿测试台", note: "FastAPI + WebSocket，接到现有应用" },
  ],
};
